## Using NumPy to perform arithmetic operations on data

In [1]:
import numpy as np
from numpy.random import randn

In [2]:
np.set_printoptions(precision=2)

##Creating Arrays

In [4]:
# creating arrays using a list
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [6]:
np.array([[10,20,30,40,50],[1,2,3,4,5]])

array([[10, 20, 30, 40, 50],
       [ 1,  2,  3,  4,  5]])

In [8]:
# creating arrays via assignment

np.random.seed(25) #: Sets the starting point for random number generation to make results repeatable.
c=36*np.random.randn(6) #Creates an array c by generating 6 random numbers from a normal distribution and multiplying them by 36.
c

array([  8.22,  36.97, -30.23, -21.28, -34.45,  -8.  ])

In [11]:
d = np.arange(1,34)
d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33])

### Multiplying matrices and basic linear algebra


In [13]:
a*10

array([10, 20, 30, 40, 50, 60])

In [14]:
c+a

array([  9.22,  38.97, -27.23, -17.28, -29.45,  -2.  ])

In [15]:
c-a

array([  7.22,  34.97, -33.23, -25.28, -39.45, -14.  ])

In [16]:
c/a

array([  8.22,  18.48, -10.08,  -5.32,  -6.89,  -1.33])